name: Backup Neon Database

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Crear carpeta de backups
        run: mkdir -p backups

      - name: Crear respaldo con PostgreSQL 17
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -v "${{ github.workspace }}/backups:/backups" \
            postgres:17 \
            bash -c 'pg_dump "$DATABASE_URL" --format=custom --file=/backups/neon-$(date +%F-%H-%M).backup'

      - name: Subir respaldo
        uses: actions/upload-artifact@v4
        with:
          name: respaldo-neon
          path: backups/